### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/cliente/1 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{

    "nome" : "Leonardo Martendal",
    "cpf" : "015643874656",
    "telefone" : "4988234567",
    "senha" : "bolinzhas",
    "compra_fiado" : 15,
    "dia_fiado" : 8

}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type: application/json

{
    "nome" : "Leonardo Barros",
    "cpf" : "12345678909",
    "telefone" : "49898989",
    "senha" : "abc",
    "compra_fiado" : 54,
    "dia_fiado" : 5

}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1